config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'home#index'
  get '/aboutus/' => 'home#aboutus'

  #User Routes
  get '/signup/' => 'user#new'
  post '/signup/' => 'user#create'

  # Session Routes
  get '/login/' => 'session#new'
  post '/login/' => 'session#create'

  get '/logout/' => 'session#destroy'

  # Password Routes
  get '/passwords' => 'passwords#edit'
  patch '/passwords/edit' => 'passwords#update'
 
  

  # Employee Routes CRUD
  get '/employees/' => 'employees#index'
  get '/new_employee/' => 'employees#new'
  post '/new_employee/' => 'employees#create'

  get '/edit/:id', to: 'employees#edit', as: 'edit'
  patch '/update/:id', to: 'employees#update', as: 'update'

  get '/destroy/:id', to: 'employees#destroy', as: 'destroy'

  get '/employeebackup/' => 'employee_backups#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/employee.rb
class Employee < ApplicationRecord

  # Validation for presence
  validates :first_name, :last_name, :email, :address, presence: true
      
  # Validation for email format and uniqueness
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
      
  # Validation for number (assuming it's a phone number or similar)
  validates :number, numericality: { only_integer: true }, allow_blank: true

      
      
      
end

app/models/employee_backup.rb
class EmployeeBackup < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  #Validation for emails
  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Enter a valid email address" }
  #Validation for passwords
  validates :password, length: { minimum: 6 }, allow_blank: true
  validates :password, format: { with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W])/, message: "must include at least one lowercase letter, one uppercase letter, one digit, and one special character" }






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user
  helper_method :require_user_logged_in?


  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end

  end
  
  def require_user_logged_in!
    redirect_to signin_path, alert: "You must be signed in to do that." if Current.user.nil?
  end

end

app/controllers/employee_backups_controller.rb
class EmployeeBackupsController < ApplicationController

  def index
    @employee_backups = EmployeeBackup.all
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    if !Current.user
        redirect_to login_path, alert: "You must be signed in to do that."
    else
        @employee = Employee.all

    end

  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: "Employee was successfully created."
    else
        redirect_to new_employee_path, alert: "Employee was not created."
    end
  end
  
  def destroy
    @employee = Employee.find_by(id: params[:id])
    if @employee.destroy
      redirect_to employees_path, notice: "Employee was successfully deleted."
    else
      redirect_to employees_path, alert: "Employee was not deleted."
    end
  end

  def edit
    @employee = Employee.find_by(id: params[:id])
  end

  def update
    @employee = Employee.find_by(id: params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path, notice: "Employee was successfully updated."
    else
      redirect_to employees_path, alert: "Employee was not updated."
    end
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email, :number, :address)
  end

    
  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  
  end

  def aboutus
  
  end  
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  before_action :require_user_logged_in!
  def edit
    @user = Current.user
  end

  def update

    if Current.user.update(password_params)
        redirect_to root_path, notice: "Password updated successfully!"
    else
        render :edit
    end
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? &&user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to employees_path, notice: "You have successfully logged in!"

    else
      redirect_to login_path, alert: "There was a problem logging in. Please try again."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have successfully logged out!"
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "You have successfully signed up!"
    else
      puts @user.errors.full_messages
      redirect_to signup_path, notice: "There was a problem signing up. Please try again."
    end


  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_backups_helper.rb
module EmployeeBackupsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/employee_backups/index.html.erb
<div class="alert alert-info" role="alert">
  <h2>Employee Backup List</h2>
</div>

    <table class="table table-hover">
        <thead>
          <tr>
            <th>First Name   </th>
            <th>Last Name  </th>
            <th>Email  </th>
            <th>Number  </th>
            <th>Address </th>
          </tr>
        </thead>
        <tbody>
          <% @employee_backups.each do |em| %>
            <tr>
              <td><%= em.first_name %></td>
              <td><%= em.last_name %></td>
              <td><%= em.email %></td>
              <td><%= em.number %></td>
              <td><%= em.address %></td>        
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/employees/edit.html.erb
<br>
<h2> Add Employee </h2>

<%= form_with model: @employee, url: update_path(@employee), method: :patch do |f| %>
    <%= f.label :First_Name , class: "form-label"%>
    <%= f.text_field :first_name, placeholder:"Enter your First Name", class: "form-control" %>
    <br>
    <%= f.label :Last_Name , class: "form-label" %>
    <%= f.text_field :last_name, placeholder:"Enter your Last Name" , class: "form-control"%>
    <br>
    <%= f.label :Email , class: "form-label"%>
    <%= f.text_field :email, placeholder:"Enter your Email" , class: "form-control"%>
    <br>
    <%= f.label :Phone_Number , class: "form-label" %>
    <%= f.number_field :number, placeholder:"Enter your Phone Number" , class: "form-control"%>
    <br>
    <%= f.label :Address , class: "form-label"%>
    <%= f.text_field :address, placeholder:"Enter your Address" , class: "form-control"%>

    <br>
    <%= f.submit class:"btn btn-primary" %>
<% end %>

    

app/views/employees/index.html.erb
<div class="alert alert-info" role="alert">
  <h2>Employee List</h2>
</div>

    <table class="table table-hover">
        <thead>
          <tr>
            <th>First Name   </th>
            <th>Last Name  </th>
            <th>Email  </th>
            <th>Number  </th>
            <th>Address </th>
          </tr>
        </thead>
        <tbody>
          <% @employee.each do |em| %>
            <tr>
              <td><%= em.first_name %></td>
              <td><%= em.last_name %></td>
              <td><%= em.email %></td>
              <td><%= em.number %></td>
              <td><%= em.address %></td>
              <td> <%= link_to "Edit", edit_path(em.id), method: :get, class:"btn btn-success" %></td>
              <td><%= link_to "Delete", destroy_path(em.id), method: :get, class:"btn btn-danger" %></td>
              
            </tr>
          <% end %>
        </tbody>
      </table>
    
     
<%= link_to "New Employee", new_employee_path, class:"btn btn-primary" %>

app/views/employees/new.html.erb
<br>
<h2>Add New Employee</h2>

<%= form_with model: @employee, url: new_employee_path do |f| %>
    <%= f.label :First_Name , class: "form-label"%>
    <%= f.text_field :first_name, placeholder:"Enter your First Name", class: "form-control" %>
    <br>
    <%= f.label :Last , class: "form-label" %>
    <%= f.text_field :last_name, placeholder:"Enter your Last Name" , class: "form-control"%>
    <br>
    <%= f.label :Email , class: "form-label"%>
    <%= f.text_field :email, placeholder:"Enter your Email" , class: "form-control"%>
    <br>
    <%= f.label :Phone_Number , class: "form-label" %>
    <%= f.number_field :number, placeholder:"Enter your Phone Number" , class: "form-control"%>
    <br>
    <%= f.label :Address , class: "form-label"%>
    <%= f.text_field :address, placeholder:"Enter your Address" , class: "form-control"%>
    <br>
    <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/home/_headers.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="padding: 0.5% 4%;">
    <a class="navbar-brand" href="#">Employee Stack</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to "Signup", signup_path, class: "nav-link" %>
        </li>  
        
         <li class="nav-item">
          <%= link_to "About us", aboutus_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 column-gap-3">
       
        <%= link_to "Login",login _path, class:"text-decoration-none" %>
        <%= link_to "Sign Up", signup_path, class:"text-decoration-none" %>
        <% end %>
        
      </ul>
    </div>
  </nav>

app/views/home/aboutus.html.erb
<h1> About Us </h1>

app/views/home/index.html.erb
<div class="container">
     <div class="jumbotron">
        <h2>Employee Stack</h2>
        <p>Employee Stack is a simple web application that allows you to manage your employees.</p>
        <br>
        <p><%= link_to "Sign up now!", signup_path, class: "btn btn-primary btn-lg" %></p>
    </div
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Stack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  

  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/new.html.erb
<h1>Sign In</h1>
<br>
<%= form_with url: login_path do |form| %>

<%= form.label :Email, class: "form-label"%>
<%= form.text_field :email, placeholder:"Enter your Email" , class: "form-control"  %>
<br>
<%= form.label :Password, class: "form-label"%>
<%= form.text_field :password, placeholder:"Enter your Password" , class: "form-control" %> 
<br>   
<%= form.submit "Sign in", class:"btn btn-primary"%>

<% end  %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success">
    <%= flash[:notice] %>
</div>

<% end %>


<% if flash[:alert] %>
<div class="alert alert-warning">
    <%= flash[:alert] %>
</div>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Employee Stack", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About US", aboutus_path, class: "nav-link" %>
      </li>
      <% if Current.user %>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, method: :get, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Employees", employees_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/user/new.html.erb
<h1>Sign Up</h1>
<br>
<%= form_with model: @user, url: signup_path do |form| %>

  <% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <% end %>
    
  <%= form.label :email, "Email", class: "form-label" %>
  <%= form.email_field :email, placeholder: "Enter your Email", class: "form-control" %>
  <br>
  <%= form.label :password, "Password", class: "form-label" %>
  <%= form.password_field :password, placeholder: "Create your Password", class: "form-control" %>
  <br>
  <%= form.label :password_confirmation, "Confirm Password", class: "form-label" %>
  <%= form.password_field :password_confirmation, placeholder: "Retype your Password", class: "form-control" %>
  <br>
  <%= form.submit "Sign Up", class: "btn btn-primary" %>

<% end %>